# Generated by Django 4.1.1 on 2022-10-30 15:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlokTestlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.CharField(max_length=15)),
                ('week_code', models.CharField(max_length=100)),
                ('fio', models.CharField(max_length=100)),
                ('first_block', models.CharField(max_length=100)),
                ('second_block', models.CharField(max_length=100)),
                ('fan1', models.IntegerField()),
                ('fan2', models.IntegerField()),
                ('ona_tili', models.IntegerField()),
                ('tarix', models.IntegerField()),
                ('matematika', models.IntegerField()),
                ('ball', models.CharField(max_length=10)),
                ('local_number', models.CharField(max_length=30)),
                ('sms_status', models.CharField(max_length=10)),
                ('global_number', models.CharField(max_length=15)),
                ('global_id', models.CharField(max_length=10)),
                ('week_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Blok Testlar',
                'verbose_name_plural': 'Blok Testlar',
            },
        ),
        migrations.CreateModel(
            name='FanTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_kodi', models.CharField(max_length=100)),
                ('fan_nomi', models.CharField(max_length=100)),
                ('oquvchi', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('teacher', models.CharField(default="G'ulomov Azizbek", max_length=50)),
                ('test_soni', models.IntegerField()),
                ('togri_javoblar', models.IntegerField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fan Testlar',
                'verbose_name_plural': 'Fan Testlar',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter subject name', max_length=100, verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Fanlar ',
                'verbose_name_plural': 'Fanlar ',
                'db_table': 'Fan',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="O'qituvchi ism sharifi ...", max_length=100, verbose_name='Ism sharif')),
                ('one_id', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(help_text='Telefon raqamini kiriting ...', max_length=50, verbose_name='Telefon raqami')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.subject')),
            ],
            options={
                'verbose_name': "O'qituvchi ",
                'verbose_name_plural': "O'qituvchilar ",
                'db_table': "O'qituvchi",
            },
        ),
    ]
