# Generated by Django 4.1.1 on 2022-10-30 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nomini kiriiting ...', max_length=100, verbose_name='Nomi')),
                ('region', models.CharField(choices=[('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ("Farg'ona", "Farg'ona"), ('Jizzax', 'Jizzax'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Qashqadaryo', 'Qashqadaryo'), ("Qoraqalpog'iston", "Qoraqalpog'iston"), ('Samarqand', 'Samarqand'), ('Sirdaryo', 'Sirdaryo'), ('Surxondaryo', 'Surxondaryo'), ('Xorazm', 'Xorazm'), ('Toshkent', 'Toshkent')], default='Qashqadaryo', help_text='Viloyatni kiriting ...', max_length=100, verbose_name='Region')),
                ('address', models.CharField(help_text='Manzilni kiriting ...', max_length=100, verbose_name='Manzil')),
                ('phone', models.CharField(help_text='Telefon raqamni kiriting ...', max_length=100, verbose_name='Telefon raqam')),
            ],
            options={
                'verbose_name': 'Ota ona ',
                'verbose_name_plural': 'Ota onalar ',
                'db_table': 'Ota ona',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ism sharifni kiriting ...', max_length=100, verbose_name='Ism sharif')),
                ('address', models.CharField(help_text='Manzilni kiriting ...', max_length=100, verbose_name='Manzil')),
                ('image', models.ImageField(help_text='Rasm yuklang ...', upload_to='student-image', verbose_name='Image')),
                ('phone', models.CharField(help_text='Telefon raqam', max_length=100, verbose_name='Telefon raqam')),
                ('one_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.parent')),
            ],
            options={
                'verbose_name': "O'quvchi  ",
                'verbose_name_plural': "O'quvchilar ",
                'db_table': "O'quvchi",
            },
        ),
    ]
