# Generated by Django 4.1.1 on 2022-10-30 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sinf nomini kiriting ...', max_length=100, verbose_name='Sinf nomi')),
                ('lesson_time', models.TextField(help_text='Dars vaqtini kiriting', verbose_name='Dars vaqti')),
                ('student', models.ManyToManyField(to='students.student')),
            ],
            options={
                'verbose_name': 'Sinfxona ',
                'verbose_name_plural': 'Sinfxonalar ',
                'db_table': 'Sinfxona',
            },
        ),
        migrations.CreateModel(
            name='Tuitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ism sharifini kiriting ...', max_length=100, verbose_name='Ism sharif')),
                ('phone', models.CharField(help_text='Telefon raqamini kiriting ...', max_length=100, verbose_name='Telefon raqami')),
                ('about', models.TextField(help_text="O'qituvchi haqida ma'lumot", verbose_name="O'qutuvchi haqida")),
            ],
            options={
                'verbose_name': "O'qituvchi ",
                'verbose_name_plural': "O'qituvchilar ",
                'db_table': 'Tuitor',
            },
        ),
        migrations.CreateModel(
            name='Davomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bool', models.BooleanField(default=False)),
                ('sinf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', to_field='one_id')),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomatlar',
                'db_table': 'Davomat ',
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='tuitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.tuitor'),
        ),
    ]
